INSERT INTO `usuarios` (`id`, `nombre_completo`, `correo`, `usuario`, `contrasena`) VALUES 
(NULL, '111', 'GARZON PARRA SANDRA LILIANA', 'sandra.garzon@prosalon.com.co', 'sandra.garzon@prosalon.com.co', '12345678'),
(NULL, '111', 'CRUZ FAJARDO ERICA', 'erica.cruz@prosalon.com.co', 'erica.cruz@prosalon.com.co', '12345678'),
(NULL, '111', 'GALVIS VILLAMIZAR RICARDO', 'ricardo.galvis@prosalon.com.co', 'ricardo.galvis@prosalon.com.co', '12345678'),
(NULL, '111', 'TORRALBA TORRES CRISTIAN DAVID', 'cristian.torralba@prosalon.com.co', 'cristian.torralba@prosalon.com.co', '12345678'),
(NULL, '111', 'GARAVITO PEREZ SERGIO ANDRES', 'sergio.garavito@prosalon.com.co', 'sergio.garavito@prosalon.com.co', '12345678'),
(NULL, '111', 'GONZALEZ SANCHEZ PATRICIA', 'patricia.gonzalez@prosalon.com.co', 'patricia.gonzalez@prosalon.com.co', '12345678'),
(NULL, '111', 'PRIETO MONGUA JESICA LORENA', 'jesica.prieto@prosalon.com.co', 'jesica.prieto@prosalon.com.co', '12345678'),
(NULL, '111', 'CHAMORRO CORAL RUTH LILIANA', 'ruth.chamorro@prosalon.com.co', 'ruth.chamorro@prosalon.com.co', '12345678'),
(NULL, '111', 'SERRANO CAYCEDO YURI ESPERANZA', 'yuri.serrano@prosalon.com.co', 'yuri.serrano@prosalon.com.co', '12345678'),
(NULL, '111', 'MEJIA GRAJALES PAULA ANDREA', 'paula.mejia@prosalon.com.co', 'paula.mejia@prosalon.com.co', '12345678'),
(NULL, '111', 'LOPEZ RAMIREZ JOSE LUIS', 'jose.lopez@prosalon.com.co', 'jose.lopez@prosalon.com.co', '12345678'),
(NULL, '111', 'SANCHEZ MEJIA FREDY', 'fredy.sanchez@prosalon.com.co', 'fredy.sanchez@prosalon.com.co', '12345678'),
(NULL, '111', 'DIAZ SALAZAR KAREN', 'karen.diaz@prosalon.com.co', 'karen.diaz@prosalon.com.co', '12345678'),
(NULL, '111', 'ARANGO GOMEZ ADELAIDA', 'adelaida.arango@prosalon.com.co', 'adelaida.arango@prosalon.com.co', '12345678'),
(NULL, '111', 'MARTINEZ MARTINEZ MARIAM CAMILA', 'mariam.martinez@prosalon.com.co', 'mariam.martinez@prosalon.com.co', '12345678'),
(NULL, '111', 'CALDERON MATIAS RICHARD', 'richard.calderon@prosalon.com.co', 'richard.calderon@prosalon.com.co', '12345678'),
(NULL, '111', 'OSMA FONSECA JENNY ALEXANDRA', 'jenny.osma@prosalon.com.co', 'jenny.osma@prosalon.com.co', '12345678'),
(NULL, '111', 'SERNA BERMUDES CAROLL MARIA', 'caroll.serna@prosalon.com.co', 'caroll.serna@prosalon.com.co', '12345678'),
(NULL, '111', 'BARRETO TORO MARIA ALEJANDRA', 'maria.barreto@prosalon.com.co', 'maria.barreto@prosalon.com.co', '12345678'),
(NULL, '111', 'QUIROGA MORENO MARIA FERNANDA', 'maria.quiroga@prosalon.com.co', 'maria.quiroga@prosalon.com.co', '12345678'),
(NULL, '111', 'PORRAS FIGUEROA LAURA ANDREA', 'laura.porras@prosalon.com.co', 'laura.porras@prosalon.com.co', '12345678'),
(NULL, '111', 'VILLEGAS GIRALDO CAMILA', 'camila.villegas@prosalon.com.co', 'camila.villegas@prosalon.com.co', '12345678'),
(NULL, '111', 'SALAMANCA BOSSA DAYRA LORENA', 'dayra.salamanca@prosalon.com.co', 'dayra.salamanca@prosalon.com.co', '12345678'),
(NULL, '111', 'SAAVEDRA ARIAS XIMENA ANDREA', 'ximena.saavedra@prosalon.com.co', 'ximena.saavedra@prosalon.com.co', '12345678'),
(NULL, '111', 'MOLANO CORTES ANDRES GUILLERMO', 'andres.molano@prosalon.com.co', 'andres.molano@prosalon.com.co', '12345678'),
(NULL, '111', 'TRIANA DIAZ CINDY SERLLEY', 'cindy.triana@prosalon.com.co', 'cindy.triana@prosalon.com.co', '12345678'),
(NULL, '111', 'HERRERA OBREGON LINA VANESSA', 'lina.herrera@prosalon.com.co', 'lina.herrera@prosalon.com.co', '12345678'),
(NULL, '111', 'ASPRILLA CORDOBA TATIANA', 'tatiana.asprilla@prosalon.com.co', 'tatiana.asprilla@prosalon.com.co', '12345678'),
(NULL, '111', 'GARCIA CASTAÑO ALICIA MARGARITA', 'alicia.garcia@prosalon.com.co', 'alicia.garcia@prosalon.com.co', '12345678'),
(NULL, '111', 'BELTE GONZALEZ MELANIE JEAN', 'melanie.belte@prosalon.com.co', 'melanie.belte@prosalon.com.co', '12345678'),
(NULL, '111', 'BARRAGAN BAUTISTA PAULA NATHALIA', 'paula.barragan@prosalon.com.co', 'paula.barragan@prosalon.com.co', '12345678'),
(NULL, '111', 'BECERRA GERMAN ALEJANDRO', 'alejandro.becerra@prosalon.com.co', 'alejandro.becerra@prosalon.com.co', '12345678'),
(NULL, '111', 'PEÑA PEDROZA MARIA CAMILA', 'maria.peña@prosalon.com.co', 'maria.peña@prosalon.com.co', '12345678'),
(NULL, '111', 'LACOUTURE DAZA DIANAMARIA DESIREE', 'dianamaria.lacouture@prosalon.com.co', 'dianamaria.lacouture@prosalon.com.co', '12345678'),
(NULL, '111', 'ORTIZ OCAMPO DANIELA', 'daniela.ortiz@prosalon.com.co', 'daniela.ortiz@prosalon.com.co', '12345678'),
(NULL, '111', 'FUNEME AMAYA LAURA ESTEFANIA', 'laura.funeme@prosalon.com.co', 'laura.funeme@prosalon.com.co', '12345678'),
(NULL, '111', 'BLANCO MOLINA VIVIANA', 'viviana.blanco@prosalon.com.co', 'viviana.blanco@prosalon.com.co', '12345678'),
(NULL, '111', 'MARULANDA DYLAN SANTIAGO', 'santiago.marulanda@prosalon.com.co', 'santiago.marulanda@prosalon.com.co', '12345678'),
(NULL, '111', 'PATIÑO MARTINEZ JUAN SEBASTIAN', 'juan.patiño@prosalon.com.co', 'juan.patiño@prosalon.com.co', '12345678'),
(NULL, '111', 'SALCEDO GONZALEZ EDWIN SMITH', 'edwin.salcedo@prosalon.com.co', 'edwin.salcedo@prosalon.com.co', '12345678'),
(NULL, '111', 'ROA DUARTE PAOLA ANDREA', 'paola.roa@prosalon.com.co', 'paola.roa@prosalon.com.co', '12345678'),
(NULL, '111', 'RODRIGUEZ SALAZAR ANGEL FABIAN', 'angel.rodriguez@prosalon.com.co', 'angel.rodriguez@prosalon.com.co', '12345678'),
(NULL, '111', 'HERNANDEZ SOGAMOSO FRANCY YINNETH', 'francy.hernandez@prosalon.com.co', 'francy.hernandez@prosalon.com.co', '12345678'),
(NULL, '111', 'ITURRIAGO CARRASCAL LORENA', 'lorena.iturriago@prosalon.com.co', 'lorena.iturriago@prosalon.com.co', '12345678'),
(NULL, '111', 'CASTRO CALDERON JUAN CAMILO', 'juan.castro@prosalon.com.co', 'juan.castro@prosalon.com.co', '12345678'),

