INSERT INTO `usuarios` (`id`, `id_perfil`, `nombre_completo`, `correo`, `usuario`, `contrasena`) VALUES 
(NULL, '101', 'Maria Barreto', 'maria.barreto@prosalon.com.co', 'maria.barreto@prosalon.com.co', '1234'), 
(NULL, '102', 'Sandra Garzon', 'sandra.garzon@prosalon.com.co', 'sandra.garzon@prosalon.com.co', '1234'),
(NULL, '103', 'Sergio Garavito', 'sergio.garavito@prosalon.com.co', 'sergio.garavito@prosalon.com.co', '1234'),
(NULL, '104', 'Patricia Gonzalez', 'patricia.gonzalez@prosalon.com.co', 'patricia.gonzalez@prosalon.com.co', '1234'),
(NULL, '105', 'Adelaida Arango', 'adelaida.arango@prosalon.com.co', 'adelaida.arango@prosalon.com.co', '1234'),
(NULL, '106', 'Richard Calderon', 'richard.calderon@prosalon.com.co', 'richard.calderon@prosalon.com.co', '1234'),
(NULL, '107', 'Andres Molano', 'andres.molano@prosalon.com.co', 'andres.molano@prosalon.com.co', '1234'),
(NULL, '108', 'Alicia Garcia', 'alicia.garcia@prosalon.com.co', 'alicia.garcia@prosalon.com.co', '1234'),
(NULL, '109', 'Paula Barragan', 'paula.barragan@prosalon.com.co', 'paula.barragan@prosalon.com.co', '1234'),
(NULL, '110', 'Juan Patiño', 'juan.patiño@prosalon.com.co', 'juan.patiño@prosalon.com.co', '1234'),
(NULL, '111', 'Dayra Salamanca', 'dayra.salamanca@prosalon.com.co', 'dayra.salamanca@prosalon.com.co', '1234'),
(NULL, '112', 'Camila Villegas', 'camila.villegas@prosalon.com.co', 'camila.villegas@prosalon.com.co', '1234');


INSERT INTO `usuarios` (`id`, `id_perfil`, `nombre_completo`, `correo`, `usuario`, `contrasena`) VALUES 
(NULL, '101', 'Maria Barreto', 'maria.barreto@prosalon.com.co', 'maria.barreto@prosalon.com.co', '1234'), 
(NULL, '102', 'Sandra Garzon', 'sandra.garzon@prosalon.com.co', 'sandra.garzon@prosalon.com.co', '1234'),
(NULL, '103', 'Sergio Garavito', 'sergio.garavito@prosalon.com.co', 'sergio.garavito@prosalon.com.co', '1234'),
(NULL, '104', 'Patricia Gonzalez', 'patricia.gonzalez@prosalon.com.co', 'patricia.gonzalez@prosalon.com.co', '1234'),
(NULL, '105', 'Adelaida Arango', 'adelaida.arango@prosalon.com.co', 'adelaida.arango@prosalon.com.co', '1234'),
(NULL, '106', 'Richard Calderon', 'richard.calderon@prosalon.com.co', 'richard.calderon@prosalon.com.co', '1234'),
(NULL, '107', 'Andres Molano', 'andres.molano@prosalon.com.co', 'andres.molano@prosalon.com.co', '1234'),
(NULL, '108', 'Alicia Garcia', 'alicia.garcia@prosalon.com.co', 'alicia.garcia@prosalon.com.co', '1234'),
(NULL, '109', 'Paula Barragan', 'paula.barragan@prosalon.com.co', 'paula.barragan@prosalon.com.co', '1234'),
(NULL, '110', 'Juan Patiño', 'juan.patiño@prosalon.com.co', 'juan.patiño@prosalon.com.co', '1234'),
(NULL, '111', 'Dayra Salamanca', 'dayra.salamanca@prosalon.com.co', 'dayra.salamanca@prosalon.com.co', '1234'),
(NULL, '112', 'Camila Villegas', 'camila.villegas@prosalon.com.co', 'camila.villegas@prosalon.com.co', '1234'),
(NULL, '101','CRUZ FAJARDO ERICA','erica.cruz@prosalon.com.co','erica.cruz@prosalon.com.co','1234'),
(NULL, '101','ASPRILLA CORDOBA TATIANA','tatiana.asprilla@prosalon.com.co','tatiana.asprilla@prosalon.com.co','1234'),
(NULL, '101','CASTRO CALDERON JUAN CAMILO','juan.castro@prosalon.com.co','juan.castro@prosalon.com.co','1234'),
(NULL, '101','GALVIS VILLAMIZAR RICARDO','ricardo.galvis@prosalon.com.co','ricardo.galvis@prosalon.com.co','1234'),
(NULL, '101','PORRAS FIGUEROA LAURA ANDREA','laura.porras@prosalon.com.co','laura.porras@prosalon.com.co','1234'),
(NULL, '101','SALCEDO GONZALEZ EDWIN SMITH','edwin.salcedo@prosalon.com.co','edwin.salcedo@prosalon.com.co','1234'),
(NULL, '101','TORRALBA TORRES CRISTIAN DAVID','cristian.torralba@prosalon.com.co','cristian.torralba@prosalon.com.co','1234'),
(NULL, '104','CHAMORRO CORAL RUTH LILIANA','ruth.chamorro@prosalon.com.co','ruth.chamorro@prosalon.com.co','1234'),
(NULL, '104','DIAZ SALAZAR KAREN','karen.diaz@prosalon.com.co','karen.diaz@prosalon.com.co','1234'),
(NULL, '104','LOPEZ RAMIREZ JOSE LUIS','jose.lopez@prosalon.com.co','jose.lopez@prosalon.com.co','1234'),
(NULL, '104','MARTINEZ MARTINEZ MARIAM CAMILA','mariam.martinez@prosalon.com.co','mariam.martinez@prosalon.com.co','1234'),
(NULL, '104','MEJIA GRAJALES PAULA ANDREA','paula.mejia@prosalon.com.co','paula.mejia@prosalon.com.co','1234'),
(NULL, '104','PRIETO MONGUA JESICA LORENA','jesica.prieto@prosalon.com.co','jesica.prieto@prosalon.com.co','1234'),
(NULL, '104','SANCHEZ MEJIA FREDY','fredy.sanchez@prosalon.com.co','fredy.sanchez@prosalon.com.co','1234'),
(NULL, '104','SERNA BERMUDES CAROLL MARIA','caroll.serna@prosalon.com.co','caroll.serna@prosalon.com.co','1234'),
(NULL, '104','SERRANO CAYCEDO YURI ESPERANZA','yuri.serrano@prosalon.com.co','yuri.serrano@prosalon.com.co','1234'),
(NULL, '106','HERNANDEZ SOGAMOSO FRANCY YINNETH','francy.hernandez@prosalon.com.co','francy.hernandez@prosalon.com.co','1234'),
(NULL, '106','ITURRIAGO CARRASCAL LORENA','lorena.iturriago@prosalon.com.co','lorena.iturriago@prosalon.com.co','1234'),
(NULL, '106','OSMA FONSECA JENNY ALEXANDRA','jenny.osma@prosalon.com.co','jenny.osma@prosalon.com.co','1234'),
(NULL, '106','QUIROGA MORENO MARIA FERNANDA','maria.quiroga@prosalon.com.co','maria.quiroga@prosalon.com.co','1234'),
(NULL, '106','ROA DUARTE PAOLA ANDREA','paola.roa@prosalon.com.co','paola.roa@prosalon.com.co','1234'),
(NULL, '106','RODRIGUEZ SALAZAR ANGEL FABIAN','angel.rodriguez@prosalon.com.co','angel.rodriguez@prosalon.com.co','1234'),
(NULL, '107','HERRERA OBREGON LINA VANESSA','lina.herrera@prosalon.com.co','lina.herrera@prosalon.com.co','1234'),
(NULL, '107','LACOUTURE DAZA DIANAMARIA DESIREE','dianamaria.lacouture@prosalon.com.co','dianamaria.lacouture@prosalon.com.co','1234'),
(NULL, '107','TRIANA DIAZ CINDY SERLLEY','cindy.triana@prosalon.com.co','cindy.triana@prosalon.com.co','1234'),
(NULL, '108','BECERRA GERMAN ALEJANDRO','alejandro.becerra@prosalon.com.co','alejandro.becerra@prosalon.com.co','1234'),
(NULL, '108','BELTE GONZALEZ MELANIE JEAN','melanie.belte@prosalon.com.co','melanie.belte@prosalon.com.co','1234'),
(NULL, '108','PEÑA PEDROZA MARIA CAMILA','maria.peña@prosalon.com.co','maria.peña@prosalon.com.co','1234'),
(NULL, '109','BLANCO MOLINA VIVIANA','viviana.blanco@prosalon.com.co','viviana.blanco@prosalon.com.co','1234'),
(NULL, '109','FUNEME AMAYA LAURA ESTEFANIA','laura.funeme@prosalon.com.co','laura.funeme@prosalon.com.co','1234'),
(NULL, '109','MARULANDA DYLAN SANTIAGO','santiago.marulanda@prosalon.com.co','santiago.marulanda@prosalon.com.co','1234'),
(NULL, '109','ORTIZ OCAMPO DANIELA','daniela.ortiz@prosalon.com.co','daniela.ortiz@prosalon.com.co','1234'),
(NULL, '112','SAAVEDRA ARIAS XIMENA ANDREA','ximena.saavedra@prosalon.com.co','ximena.saavedra@prosalon.com.co','1234');

INSERT INTO `usuarios` (`id`, `id_perfil`, `nombre_completo`, `correo`, `usuario`, `contrasena`) VALUES 
(NULL, '116', 'PRIETO NEIZA ALIRIO', 'alirio.prieto@prosalon.com.co', 'alirio.prieto@prosalon.com.co','1234'),
(NULL, '117', 'ORTIZ HOSTOS ANDREA VIVIANA', 'andrea.ortiz@prosalon.com.co', 'andrea.ortiz@prosalon.com.co','1234'),
(NULL, '118', 'AGUILAR AGUDELO ALEJANDRA', 'alejandra.aguilar@prosalon.com.co', 'alejandra.aguilar@prosalon.com.co','1234'),
(NULL, '118', 'GIL BERMUDEZ LUISA MARIA', 'luisa.gil@prosalon.com.co', 'luisa.gil@prosalon.com.co','1234'),
(NULL, '119', 'BRAVO MUÑOZ CAMILO ARTURO', 'camilo.bravo@prosalon.com.co', 'camilo.bravo@prosalon.com.co','1234'),
(NULL, '120', 'GONZALEZ GODOY LAURA BIBIANA', 'laura.gonzalez@prosalon.com.co','laura.gonzalez@prosalon.com.co','1234'), 
(NULL, '120', 'QUINTERO ORTIZ YADIRA XIMENA', 'yadira.quintero@prosalon.com.co', 'yadira.quintero@prosalon.com.co','1234'),
(NULL, '120', 'QUIROGA PULIDO LUZ MERY', 'luz.quiroga@prosalon.com.co', 'luz.quiroga@prosalon.com.co','1234'),
(NULL, '120', 'DE LOS RIOS LENTINO CAROLINA HAYDEE', 'rios.de@prosalon.com.co', 'rios.de@prosalon.com.co','1234'),
(NULL, '120', 'BALCAZAR YENNY PATRICIA', 'patricia.balcazar@prosalon.com.co', 'patricia.balcazar@prosalon.com.co','1234'),
(NULL, '121', 'ACHURY RINCON DIEGO CAMILO', 'diego.achury@prosalon.com.co', 'diego.achury@prosalon.com.co','1234'),
(NULL, '121', 'MALDONADO BENAVIDES LEIDY PATRICIA', 'leidy.maldonado@prosalon.com.co', 'leidy.maldonado@prosalon.com.co','1234'),
(NULL, '122', 'VELANDIA MARIN JUANITA ALEJANDRA', 'juanita.velandia@prosalon.com.co', 'juanita.velandia@prosalon.com.co','1234'),
(NULL, '122', 'SUACHA LARA LIZ YINETH', 'liz.suacha@prosalon.com.co', 'liz.suacha@prosalon.com.co','1234'),
(NULL, '122', 'CARDOZO RODRIGUEZ MONICA', 'monica.cardozo@prosalon.com.co', 'monica.cardozo@prosalon.com.co','1234'),
(NULL, '123', 'GONZALEZ ORDOÑEZ DIANA PATRICIA', 'diana.gonzalez@prosalon.com.co', 'diana.gonzalez@prosalon.com.co','1234'),
(NULL, '123', 'BAQUERO CASTELLANOS JAVIER ANDRES', 'javier.baquero@prosalon.com.co', 'javier.baquero@prosalon.com.co','1234'),
(NULL, '124', 'MARTINEZ VERA MIGUEL ANGEL', 'miguel.martinez@prosalon.com.co', 'miguel.martinez@prosalon.com.co','1234');
